### ISSUE TITLE
Deployment center in Azure to use functions-container-action

### ISSUE THREAD

**Issue by davegaulke** [Azure/functions-container-action#13]
Is this action currently supported for deploying a custom container based function app to Azure? If I use deployment center in Azure to setup github actions, it generates an action that uses "azure/webapps-deploy@v2", not this action. That leads me to believe that either this action is defunct or the deployment center has a bug. The other issue is that this action has not been updated to use "publish-profile" which both functions-action and webapps-deploy support. I've tried using webapps-deploy and it seems to work fine for deploying to the production slot, but does not work for me when deploying to a different slot. I'd appreciate any advice on where to go with this.

**Comment by onlythisrose** [comment]
@davegaulke I'm wondering the same. Good to know azure/webapps-deploy@v2 works. I will try that one out.

**Comment by kaverma** [comment]
Hi @anirudhgarg , moving this to you, please reassign accordingly. Thanks.

**Comment by patelchandni** [comment]
Thank you for reporting. This feature implementation is added to list of future enhancements for this action.
https://github.com/Azure/functions-container-action/issues/31
