### ISSUE TITLE
Add publish-profile option

### ISSUE THREAD

**Issue by onlythisrose** [Azure/functions-container-action#26]
I am unable to configure AZURE_CREDENTIALS with a service principal due to company restrictions. Both azure/webapps-deploy@v2 and Azure/functions-action@v1 include a publish-profile input and this would be great to have for Azure/functions-container-action@v1 too.  Without that option, I am unable to use this action.

**Comment by boris-tarasov-maersk** [comment]
yes please! Need this too as using generic AZURE_CREDENTIALS is not suitable

**Comment by patelchandni** [comment]
Thank you for reporting. This feature implementation is added to list of future enhancements for this action.
https://github.com/Azure/functions-container-action/issues/31
