### ISSUE TITLE
what command is being executed while running this action?

### ISSUE THREAD

**Issue by boris-tarasov-maersk** [Azure/functions-container-action#28]
dear developers

I would like to know what command is being executed while running this action?
Reason I am asking is that I would like to trigger deployment of a container on demand from a command line or similar.
Also, due to limits on deployment profile parameter we cannot use this action with different spns and it would help us if we can run it manually as script job in a pipeline.
wbr, Boris

**Comment by patelchandni** [comment]
Essentially, it is using this utility to deploy the app image: https://github.com/microsoft/pipelines-appservice-lib/blob/6299870403febc525eb38b2a1a85fdb5602e9a95/src/RestUtilities/ContainerDeploymentUtility.ts#L15
