### ISSUE TITLE
Future Enhancements 

### ISSUE THREAD

**Issue by patelchandni** [Azure/functions-container-action#31]
1. Add support to use "publish profile" auth
2. Deployment center in Azure to use functions-container-action

**Comment by patelchandni** [comment]
Essentially, it is using this utility to deploy the app image: https://github.com/microsoft/pipelines-appservice-lib/blob/6299870403febc525eb38b2a1a85fdb5602e9a95/src/RestUtilities/ContainerDeploymentUtility.ts#L15

Therefore, it needs RBAC credentials to update app setting linuxFxVersion/windowsFxVersion with image name.

**Comment by aaronamm** [comment]
@patelchandni for `it needs RBAC credentials to update app setting linuxFxVersion/windowsFxVersion with image name`, does this mean we can't add `publish-profile` option to `functions-container-action`?

Can we apply implementation from `azure/webapps-deplo` which has `publish-profile` option?
I think this option is still useful for those who don't have permission to generate `RBAC credentials`. 

Thank you so much.
