### ISSUE TITLE
Upgrade to Node 16

### ISSUE THREAD

**Issue by daniel-biloglav** [Azure/functions-container-action#35]
Hi,

GitHub workflows are now showing deprecation warnings for Node 12.
![image](https://user-images.githubusercontent.com/91525102/201659841-65fc7a58-ffca-4533-8ec7-5aaa6cb7c72c.png)

See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by patelchandni** [comment]
https://github.com/Azure/functions-container-action/pull/36

**Comment by patelchandni** [comment]
Released in v1.2.0

**Comment by patelchandni** [comment]
@daniel-biloglav, please test with v1 and let us know. Thank you.

**Comment by daniel-biloglav** [comment]
@patelchandni, the new version working well.

Thanks for your support :)
