### ISSUE TITLE
Upgrade to Node 20

### ISSUE THREAD

**Issue by JosiahSiegel** [Azure/functions-container-action#47]
Node 16 has reached its [end of life](https://github.com/nodejs/Release/#end-of-life-releases). All GitHub actions to run on Node 20 by [Spring 2024.](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Comment by daniel-biloglav** [comment]
Any progress on this issue?

**Comment by patelchandni** [comment]
Part of PR: https://github.com/Azure/functions-container-action/pull/52
