### ISSUE TITLE
Private container registry usage (ACR)

### ISSUE THREAD

**Issue by marvinbuss** [Azure/functions-container-action#5]
How can we deploy a container that is not public and stored in a private container registry?
Looks like there is no input that we can provide to make this happen. Would be great, if you could show how we can achieve this with this action.

**Comment by marvinbuss** [comment]
@Hazhzeng Will this be possible in a future release?

**Comment by marvinbuss** [comment]
@N-Usha I anyone taking care of this?

**Comment by N-Usha** [comment]
For webapps, we set the container registry credentials as app settings. I assume the same should work with functions too. @Hazhzeng to confirm.

**Comment by N-Usha** [comment]
@marvinbuss - Did you try using this template: https://github.com/Azure/actions-workflow-samples/blob/master/FunctionApp/linux-container-functionapp-on-azure.yml
