### ISSUE TITLE
[question] Restarting the app service takes a long time

### ISSUE THREAD

**Issue by ryancole** [Azure/functions-container-action#9]
Hi folks,

I'm using this action to deploy my container to azure. It works fine, but it takes a long time to complete. This one step takes about 6-7 minutes, meanwhile the rest of the workflow only takes a minute or so. I don't know if 6-7 minutes is considered a long time in this case or not, but it seems to make the github actions sit out there in an "in process" state for a long time.

Here's the output of the step ...

```
Run Azure/functions-container-action@v1.0.1
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Updating App Service Configuration settings. Data: ***"linuxFxVersion":"DOCKER|***.azurecr.io/wib-workspace-functions:0.0.1"***
Updated App Service Configuration settings.
Restarting app service: xxx
Restarted app service: xxx
Successfully updated deployment History at https://xxx.scm.azurewebsites.net/api/deployments/a502f6f51c629a20cf000f9f...
Azure Function App URL: http://xxx.azurewebsites.net
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

And that above step took 7 minutes to complete. The wait seems to be after it prints `Restarted app service: xxx`. So it sits there and then prints out the deployment history line.

Is this normal?

**Comment by AmrutaKawade** [comment]
@ryancole sorry for delayed response. it this behaviour consistent?

**Comment by ryancole** [comment]
@AmrutaKawade We ended up not moving forward w/ containers. I'm not sure if if this is still an issue or not.

**Comment by AmrutaKawade** [comment]
@ryancole we will close this issue. since we are not able to repro it. will reopen if someone else faces this
